joint_limits:
  joint_6:
    has_velocity_limits: true
    max_velocity: 1.0
    has_effort_limits: true
    max_effort: 1.0

  joint_7:
    has_position_limits: false # Continuous joint
    has_velocity_limits: true
    max_velocity: 4.0
    has_effort_limits: true
    max_effort: 1.0
